### ISSUE TITLE
[BUG] Non si è creato il clickup id

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/PoliFemoBackend#201]
Non si è creato il clickup id

https://github.com/PoliNetworkOrg/PoliFemoBackend/issues/200

**Comment by angeousta** [comment]
in carico a @toto04

**Comment by toto04** [comment]
eh non hai messo uno dei tag giusti che iniziano con `type: `, ho modificato il nome del tag di default `enhancement` ed è fixato
