### ISSUE TITLE
[FEATURE] Spostare la gestione delle aule nella lib

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/PoliFemoBackend#216]
Creare 2 nuove lib

1. Cache
2. Rooms

Aggiornare il grafico delle lib ed occhio alle dipendenze circolari

**Comment by angeousta** [comment]
Questa issue contribuisce a https://app.clickup.com/t/861mzgqja

**Comment by angeousta** [comment]
Fatto in

-  https://github.com/PoliNetworkOrg/Lib_CSharp/pull/27
- https://github.com/PoliNetworkOrg/PoliFemoBackend/pull/219
- https://github.com/PoliNetworkOrg/Lib_CSharp/pull/26

**Comment by francescolf** [comment]
Chiuso in #219
