### ISSUE TITLE
[Feature Request] aggiungere colonna di tipo datetime "last_activity" ed aggiungere una routine che elimina tutti i dati di un user dopo tot anni

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemoBackend#76]

**Comment by toto04** [comment]
Task collegata: [CU-861m5dz7p](https://app.clickup.com/t/861m5dz7p)

**Comment by bob27aggiustatutto** [comment]
mi sembra superfluo dirlo ma questo comporterà dover tenere aggiornato il campo "last_activity" per ogni api che l'utente chiama
