### ISSUE TITLE
Some of the SQL schema is in italian

### ISSUE THREAD

**Issue by Eliaxie** [PoliNetworkOrg/PoliFemoBackend#84]
https://github.com/PoliNetworkOrg/PoliFemoBackend/blob/b88f4d83feefdafef952235a4289a97cde2e516c/Other/DB/DBPolifemo.SQL#L94

**Comment by francescolf** [comment]
Fixed in [06a24c1](https://github.com/PoliNetworkOrg/PoliFemoBackend/commit/06a24c1341329eaf781dac73240de5a913a003d6)
