### ISSUE TITLE
[bug] Endpoint articoli non dovrebbe rispondere con status code 404

### ISSUE THREAD

**Issue by toto04** [PoliNetworkOrg/PoliFemoBackend#88]
In caso di assenza di articoli, lo status di risposta dovrebbe comunque essere 2XX dato che la richiesta è andata a buon fine, 404 dovrebbe essere riservato per endpoint non esistenti

**Comment by francescolf** [comment]
Fixed in [6df0fe2](https://github.com/PoliNetworkOrg/PoliFemoBackend/commit/6df0fe275c49f383ce7a00700b048cd20c907004)
