### ISSUE TITLE
[rework]

### ISSUE THREAD

**Issue by Eliaxie** [PoliNetworkOrg/PoliFemoBackend#89]
Hello everyone, as you probably know we've migrated the application from a VM to a much complex system running on kubernetes.
In order to keep everything nice and tidy, me and Francesco had to make some choices regarding how the API layering (v1,...) and endpoints are managed.
As of now, endpoints are:
- /v1/*
- /swagger 

To simplify the management of the layering it has been decided that the versioning will be done outside the application, this will allow much greater flexibility (we could have commit #12345 pointing to /v1 and commit #23456 pointing 5o /v2) and ultimately simplify development. However in order to make this work we need to fix the code of the application, such that all endpoints follow this rules:
- there are no calls or fetching of static files to "/", this is because the root directly will be dedicated to the last version of the application, meaning that if you pick /cat.img you will actually be taking /stable/vLATEST/cat.img which in a layered application is not correct and could lead to very unexpected behavior and errors (you should actually be taking the cat.img routed at path /(stable or staging)/v(your version)/ )
- also the swagger interface will be layered, this is a sideffect which doesn't have any real implication so I would leave it like this

So now the question is how can you identify what is your base path in order to make calls to the correct endpoint?
Fortunately, ASPNETCORE offers the UsePathBase configuration, allowing you to set the correct basepath for all internal aspnetcore calls (if you do a call directly though you need to ensure correct use of the base path!)

And how do se set the UsePathBase configuration?
You will read an environment variable, called BASE_PATH that I will set to the application from the outside

Practically, what do you need to do?
- [ ] remove the /v1/ construct and put all endpoints in the root path
- [ ] add the UsePathBase configuration to the application as specified above
- [ ] verify that no calls are made to a specific endpoint without the correct base path
- [ ] adjust also the basepath in swagger if necessary

To verify your work, every commit in the dev branch is automatically deployed after 5 minutes to the aks.polinetwork.org/stable/v1/ endpoint.
If you have any doubt please write me or comment below the issue

**Comment by Eliaxie** [comment]
for now, I've disabled the root path at [aks.polinetwork.org](https://aks.polinetwork.org/) (I remind you that this path will contain the latest stable release) so that you can see errors popping up if you access the root dir, for example [https://aks.polinetwork.org/staging/v1/swagger/index.html](https://aks.polinetwork.org/staging/v1/swagger/index.html)

**Comment by francescolf** [comment]
Fixed in [e9e8078](https://github.com/PoliNetworkOrg/PoliFemoBackend/commit/e9e8078d1c5d3f1d88d6a7f434e3f9348946126a)
